//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPoll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialType
    {
        public int Id { get; set; }
        public string TypeName { get; set; }
        public decimal CountBrac { get; set; }
    }
}
