//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPoll.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        public int Id { get; set; }
        public int IdPartnerType { get; set; }
        public int IdPartnerName { get; set; }
        public int IdDirectors { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public int IdAddres { get; set; }
        public string INN { get; set; }
        public int Rayting { get; set; }
    
        public virtual Addres Addres { get; set; }
        public virtual Directors Directors { get; set; }
        public virtual PartnerName PartnerName { get; set; }
        public virtual PartnerType PartnerType { get; set; }
    }
}
